version: '3.1'

services:
  db:
    image: neo4j:latest
    restart: always
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
